name: Update Workflows

on:
  schedule:
    - cron: "30 3 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  update-workflows:
    name: Update Workflow References
    uses: Open-CMSIS-Pack/workflows-and-actions-collection/.github/workflows/update-workflow.yml@v1.0.2
    secrets:
      TOKEN_ACCESS: ${{ secrets.GRASCI_WORKFLOW_UPDATE }}
